### ISSUE TITLE
Would it be useful to have sub-versions for specific OBUs?

### ISSUE THREAD

**Issue by shawnisingh** [AOMediaCodec/iac#100]
Particularly for descriptor OBUs - codec configs, elements, and mix presentations - sub-versions could be a way for us to incrementally improve these descriptors without having to bump a full version.  Would this be useful?

**Comment by tdaede** [comment]
The problem is still that a decoder that understands the old ones would not understand the new ones, and for things like codec config, not being being able to understand it would make the whole stream undecodeable. I think the utility is limited, unless there are specific instances that backwards compatibility can be planned.

**Comment by shawnisingh** [comment]
Good point - this is convincing enough to me to close this issue.  Thanks!
