### ISSUE TITLE
Location and duplication of inner codec AudioSampleEntries

### ISSUE THREAD

**Issue by tdaede** [AOMediaCodec/iac#20]
Each internal decoder includes its own original AudioSampleEntry. This is potentially large, and is also not currently backwards compatible.

**Comment by cconcolato** [comment]
If you look at the `AudioSampleEntry` class, it defines:
- channel count (mandatory)
- sample rate (mandatory)
- channel layout (optional)
- DRC (optional)
- Downmix (optional)

As discussed during the call, we could specify that the channel count is the maximum channel count. For sample rate, I would imagine that all substreams have the same sample rate, as otherwise time alignment would be a problem (except in some cases). For all optional information, we could say that they should not be present or as it was suggested that they would be overridden by similar IAC information?

**Comment by sunghee-hwang** [comment]
We don't need the optional fields like OPUS-ISOBMFF.

**Comment by tdaede** [comment]
We should investigate what downmixing options (if any) are representable with existing mappings and ISOBMFF boxes.

**Comment by sunghee-hwang** [comment]
- RFC 7845 (Ogg Opus, CMF = 1) and RFC 8486 (Ambisonics, CMF = 2 or 3) provides stereo downmix matrices as spec text (not delivered)
- ISOBMFF defines 'dmix' box for downmix matricies as a child of Audio sample entry. Any M x N downmix matries and any coefficients can be delivered via this box, where, M = targetChannelCount and N = baseChannelCount. But N is not defined in this box but is defined in ChannelLayout box ('chnl').  As summarized, any M x N downmix matrices and any coefficients can be delivered by using two optional fields ChannelLayout('chnl') and DownMixInstructions('dmix') of Audio sample entry.

**Comment by cconcolato** [comment]
As discussed, we have an agreement to specify that only codec specific info is stored (no loop, no override). We might reconsider if new use cases are brought forward.

**Comment by tdaede** [comment]
The no loop approach is in the spec.
