### ISSUE TITLE
Determine whether codecs parameter should be fixed length instead of variable

### ISSUE THREAD

**Issue by tdaede** [AOMediaCodec/iac#41]

**Comment by sunghee-hwang** [comment]
I think that it should be closed unless an issue is raised due to variable of codecs parameter.

Or, 

we may compromise with the fixed length having 3 layers regardless of the actual number of layers.
For example ST(min).ST(mid).ST(max) where S is the number of surround channels and T is the number of Top channels.
ST(mid) is defined as follows:
- ST(mid) should indicate one of layers which is defined in IA_Static_Meta.
- If there is no layer between ST(min) and ST(max), then ST(mid) can be either ST(min) or ST(max).
- Else If a layer of mid layers is 3.1.2ch, then ST(mid) should indicate 3.1.2ch. Otherwise, S and T are the most closest value to (S(min) + S(max))/2 and (T(min) + T(max))/2, respectively.
